config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  post '/tinymce_assets' => 'images#create'

  # Home Page
  root 'pages#home'

  # Posts
  resources :posts

  # RESTful routes
  resources :pages, except: [:index] do
    member do
      get 'admin_panel'
    end
  end
  resources :suggestions, except: [:show, :edit]

end

app/views/pages/_form.html.erb
<div class="col-sm-6">
  <%= form_for(@page) do |f| %>
    <% if @page.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

        <ul>
          <% @page.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <fieldset class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </fieldset>

      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_image_fields.html.erb
<div class="nested-fields banner-img-admin">
  <%= image_tag f.object.file, class: "img-thumb" %><br>
  <%= f.file_field :file %><br>
  <%= link_to_remove_association button_tag('Remove Image', type: "button"), f %><br>
</div>

app/views/pages/_section_fields.html.erb
<div class="container">
  <div class="nested-fields">
    <div class="row">
      <h4><%= f.label :title %>
      <%= f.text_field :title, size: 40 %></h4>
    </div>
    <div class="row">
      <h4><%= f.label :order %>
      <%= f.number_field :order, min: 1, max: @page.sections.count %>
      </h4>
    </div>

    <div class="row">
      <h4><%= f.label :content %>
      <%= f.text_area :content, class: "tinymce", rows: 30, cols: 30 %>
      <%= tinymce %>
      </h4>
      <%= link_to_remove_association button_tag('Remove Section', type: "button"), f %>
    </div>
  </div>
</div>

app/views/pages/admin_panel.html.erb
<% if !admin_signed_in? %>
	<meta http-equiv="refresh" content="0; URL=../../admins/sign_in">
<% else %>
<div class="container">
  <div class="col-sm-12">
    <%= form_for(@page, html: {multipart: true}) do |f| %>
      <% if @page.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

          <ul>
            <% @page.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div id="admin_images">
        <h2>Page Banner Images</h2>
        <hr>
        <%= f.fields_for :images do |image| %>
          <%= render 'image_fields', f: image %>
        <% end %>
        <div class="links">
          <hr>
          <%= link_to_add_association button_tag('Add Banner Image', type: "button"), f, :images %>
        </div>
      </div>

      <div id="admin_form">
        <h2>Page Title:
          <%= f.text_field :title %></h2>
        <hr>
        <h2>Sections:</h2>
        <hr>
        <div id="sections">
          <%= f.fields_for :sections do |section| %>
            <%= render 'section_fields', locals: {section: section}, f: section  %>
          <% end %>
          <hr>
          <div class="links">
                  <%= link_to_add_association button_tag('Add Section', type: "button"), f, :sections %>
          </div>
        </div>
        <br>
        <div class="actions">
          <%= f.submit 'Submit', :class => "btn-primary" %>
        </div>
      </div>
  </div>
<% end %>

<div class="col-sm-12">
        <br> <%= link_to button_tag('Go Back', type: "button"), @page %>
		  <p><br></p> 
</div>
</div>
<% end %>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/1.3.2/sweetalert2.min.css">
<script src="https://cdn.jsdelivr.net/sweetalert2/1.3.2/sweetalert2.min.js"></script>

<script>
    <% if flash then %>
      <% if flash.alert then %>
          sweetAlert(
            'Success',
            'Your changes have been updated',
            'success'
          )
      <% end %>
    <% end %>
</script>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<div class="col-sm-12">
  <%= link_to 'Back', pages_path %>
</div>

app/views/pages/home.html.erb
<div id="page-content-wrapper">
  <div class="title-overlay">
    <h1><%= @page.title if @page %></h1> 
	<div class="carousel"> 
      <% @images.each do |img| %>
        <%= link_to Page.find(img.page_id) do %>
          <div style="background-image: url(<%= img.file %>);" class="slick-track"></div>
        <% end %>
      <% end %>
    </div>
  </div>


	<div class="jumbotron">
    <div class="container">
	<% if admin_signed_in? %>
       	  <div class="row">
          <br />
          <%= link_to "Edit Page", admin_panel_page_path(@page), class: "btn btn-primary" %>
       </div>
    <% end %>
		<% if @page %>
      <% @page.sections.each_with_index do |section,i| %>
        <div class="home_section">
          <h2><%= section.title %></h2>
          <p><%= section.content.html_safe %></p>
        </div>
      <% end %>
		<% end %>
    </div>

  </div><!-- /.jumbotron -->
</div>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<div class="col-sm-12">
  <%= link_to 'Back', pages_path %>
</div>

app/views/pages/show.html.erb
<div id="page-content-wrapper">
  <div class="title-overlay">
    <h1><%= @page.title %></h1>      
    <% if !@images.empty? %>
      <div class="carousel"> 
        <% @images.each do |img| %>
          <div style="background-image: url(<%= img.file %>);" class="slick-track"></div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="container">
    <% if admin_signed_in? %>
      <div class="row">
        <br />
        <%= link_to "Edit Page", admin_panel_page_path, class: "btn btn-primary" %>
      </div>
    <% end %>


    <% @sections.each do |section| %>
      <div class="row main-row">
        <div class="col-xs-12">
          <h2 class="page-header"><%= section.title %></h2>
          <span>
            <%= section.content.html_safe %>
          </span>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/pages/suggestionadmin.html.erb
<% content_for :title, @page.title %>

<div id="page-content-wrapper">
    <div class="container">
        <div class="row">
            <div class=".col-md-2"></div>
            <div class=".col-md-8">
                <table class="table">
                    <tr>
                        <th>Suggestion</th>
                        <th>Viewed</th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </div>
            <div class=".col-md-2"></div>
        </div>
    </div>
</div>