config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  post '/tinymce_assets' => 'images#create'

  # Home Page
  root 'pages#home'

  # Posts
  resources :posts

  # RESTful routes
  resources :pages, except: [:index] do
    member do
      get 'admin_panel'
    end
  end
  resources :suggestions, except: [:show, :edit]

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
	validates :name, :email ,:content, presence: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:edit, :update, :destroy]
  before_action :admin_signed_in?, only: [:index, :new, :edit, :create, :update, :destroy]

  def index
    @suggestions = Suggestion.all
  end

  def new
    @suggestion = Suggestion.new
    @images = Image.where.not(page_id: nil)
    @images = @images.shuffle
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)
    if @suggestion.save
      flash.alert = true #flash variable, prompts feedback to the user that the submission was succesfull
      #redirect_to root_path, notice: 'Suggestion was successfully created!'
      #we redirect back to the suggestion submission page
      redirect_to action: "new"
    else
    	@images = Image.where.not(page_id: nil)
   	@images = @images.shuffle
	render :new, notice: 'Section was not able to be created!'
    end
  end

  def update
    if @suggestion.update(suggestion_params)
      redirect_to @suggestion, notice: 'Suggestion was successfully updated!'
    else
	@images = Image.where.not(page_id: nil)
	@images = @images.shuffle
	render :new, notice: 'Section was not able to be updated!'
    end
  end

  def destroy
    @suggestion.destroy
    @suggestions = Suggestion.all
    render :index
  end

  private
    
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    def suggestion_params
      params.require(:suggestion).permit(:content, :email, :name)
    end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/index.html.erb
<% if !admin_signed_in? %>
   <meta http-equiv="refresh" content="0; URL=../../admins/sign_in">
<% else %>
<div id="page-content-wrapper">
    <div class="container">
        <div class="row">
            <div class=".col-md-2"></div>
            <div class=".col-md-8">
                <table class="table">
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Content</th>
                    </tr>
                    <% @suggestions.each do |suggestion| %>
                    <tr>
                        <td><%= suggestion.name %></td>
                        <td><%= mail_to suggestion.email %></td>
                        <td><%= suggestion.content %></td>
                        <td><%= link_to 'Remove', suggestion_path(suggestion), data: {:confirm => 'Are you sure?'}, action: :destroy, method: :delete %>
                        </tr>
                        <% end %>
                    </table>
                </div>
                <div class=".col-md-2"></div>
            </div>
        </div>
    </div>
<% end %>

app/views/suggestions/new.html.erb
<% content_for :title, "Suggestions" %>
<div id="page-content-wrapper">
	<div class="title-overlay">
		<h1>Suggestions</h1>
   	<% if !@images.empty? || !@images.nil? %>

    	<div class="carousel">
      	<% @images.each do |img| %>
        		<div style="background-image: url(<%= img.file %>);" class="slick-track"></div>
      	<% end %>
    	</div>
    	<% end %>
	</div>
</div>
<div class="container">
<% if admin_signed_in? %>
  <div class="row">
    <br />
  <%= link_to "View Suggestions", suggestions_path, class: "btn btn-primary" %>
  </div>
<% end %>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/1.3.2/sweetalert2.min.css">
<script src="https://cdn.jsdelivr.net/sweetalert2/1.3.2/sweetalert2.min.js"></script>

<script>
    <% if flash then %>
			<%if @suggestion == "" then %>
            <%= f.text_field(:name, class: "form-control", placeholder: "Enter your name")%>
			<% end %>
        <% if flash.alert then %>
            sweetAlert(
              'Thank you',
              'We have received your suggestion',
              'success'
            )
        <% end %>
    <% end %>
</script>

    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <h3>Please write a suggestion.</h3>
            As the Responsible Mining Initiave we care about the oppinion of our viewers, please feel free to write a suggestion about the content displayed in our site or other concerns you may have. Thank you! <br><br>
        </div>
        <div class="col-sm-2"></div>
    </div>
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <%= form_for @suggestion do |f| %>
                <% if @suggestion.errors.any? %>
                  <div id="error_explanation" class="alert alert-danger">
                    <ul>
                      <% @suggestion.errors.full_messages.each do |message| %>
                        <li>
                            <span class="glyphicon glyphicon-exclamation-sign"><%= message %></span>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <fieldset class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field(:name, class: "form-control", placeholder: "Enter your name")%>
                </fieldset>

                <fieldset class="form-group">
                    <%= f.label(:email, "Email address")%>
                    <%= f.text_field(:email, class:"form-control", placeholder:"Enter your email")%>
                    <small class="text-muted">We'll never share your email with anyone else.</small>
                </fieldset>

                <fieldset class="form-group">
                    <%= f.label(:content, "Suggestions")%>
                    <%= f.text_area(:content, class:"form-control")%>
                </fieldset>
                <button type="submit" class="btn btn-primary" padding="0x 0x 100x 0x">Submit</button>
					<p><br></p>
            <% end %>
        </div>
        <div class="col-sm-2"></div>
        <br>
    </div>
</div>