config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  post '/tinymce_assets' => 'images#create'

  # Home Page
  root 'pages#home'

  # Posts
  resources :posts

  # RESTful routes
  resources :pages, except: [:index] do
    member do
      get 'admin_panel'
    end
  end
  resources :suggestions, except: [:show, :edit]

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'RMI', root_path, class: "navbar-brand text-muted" %>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li  style="font-size:11px"><%= link_to 'Mining Life Cycle', @mining_life_cycle %></li>
          <li  style="font-size:11px"><%= link_to 'Commodity Types', @commodity_types %></li>
          <li  style="font-size:11px"><%= link_to 'Mining Issues', @mining_issues %></li>
          <li  style="font-size:11px"><%= link_to 'Societal Impacts', @societal_impacts %></li>
          <li  style="font-size:11px"><%= link_to 'Regulatory Framework', @regulatory_framework %></li>
          <li  style="font-size:11px"><%= link_to 'Suggestions', new_suggestion_path %></li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RMI <%= yield(:title) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  </head>
  <body>

    <header>
      <%= render 'layouts/nav' %>
    </header>

    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>

    <main>
      <%= yield %>
    </main>

    <footer>
      <div class="container footer-container">
        <div class="col-xs-12">
          <% if admin_signed_in? %>
                 <%= link_to "Admin Sign Out", destroy_admin_session_path, method: :delete %>
               <% else %>
                <%= link_to "Administrator Login", admin_session_path %>
              <% end %>
          </p>Copyright &copy; 2016. All Rights Reserved.</p>
        </div>
      </div>
    </footer>

  </body>
</html>